import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'zh' | 'en' | 'fr' | 'es' | 'it';

export const languages: { [key in Language]: string } = {
  zh: '简体中文',
  en: 'English',
  fr: 'Français',
  es: 'Español',
  it: 'Italiano',
};

const translations: Record<Language, Record<string, string>> = {
  zh: {
    app_name: "PDF 大师",
    pro_badge: "专业版",
    home: "首页",
    edit_pdf: "PDF 编辑器",
    merge_pdf: "合并 PDF",
    split_pdf: "拆分 PDF",
    img_to_pdf: "图片转 PDF",
    extract_images: "提取图片",
    convert_pdf: "格式转换",
    nav_edit_organize: "编辑与整理",
    nav_smart_tools: "智能工具箱",
    hero_title: "全能 PDF 处理工具箱",
    hero_desc: "基于浏览器本地处理，安全高效。为您提供智能的文档处理体验。无需上传文件到服务器。",
    start_edit: "立即开始编辑",
    popular_tools: "热门工具",
    tool_desc_edit: "添加文本、图片、形状、水印，或裁剪页面。支持图章和签名。",
    tool_desc_merge: "将多个 PDF 文件合并为一个有序的文档。支持拖拽排序。",
    tool_desc_split: "按页面范围拆分文档，或提取特定页面为新文件。",
    tool_desc_img2pdf: "将 JPG、PNG 图片转换为高质量的 PDF 文档。支持批量转换。",
    tool_desc_convert: "利用 AI 技术将 PDF 转换为 Word、Excel 或文本格式。",
    tool_desc_extract_img: "从 PDF 文档中提取所有图片并保存为 JPG 或 PNG。",
    feature_privacy: "隐私安全",
    feature_privacy_desc: "文件在本地浏览器处理，无需上传",
    feature_speed: "极速处理",
    feature_speed_desc: "基于 WebAssembly，性能接近原生应用",
    feature_ai: "AI 驱动",
    feature_ai_desc: "集成 Google Gemini 模型辅助处理",
    upload_click_drag: "点击或拖拽文件到此处",
    upload_release: "松开鼠标上传",
    upload_formats: "支持格式",
    merge_title: "合并 PDF 文件",
    merge_desc: "几秒钟内将多个 PDF 文件合并为一个文档。",
    merge_upload_label: "拖放 PDF 到此处进行合并",
    merge_selected_files: "已选文件",
    merge_btn: "立即合并 PDF",
    merge_btn_processing: "正在合并...",
    split_title: "拆分或提取页面",
    split_desc: "将 PDF 拆分为多个文件或提取特定页面。",
    split_upload_label: "上传要拆分的 PDF",
    split_change_file: "更换文件",
    split_mode_split: "拆分为文件",
    split_mode_split_desc: "将范围保存为单独的 PDF",
    split_mode_extract: "提取为单个文件",
    split_mode_extract_desc: "将范围合并为一个 PDF",
    split_range_label: "页面范围",
    split_range_placeholder: "例如： 1-3, 5, 8-10",
    split_range_help: "使用逗号分隔多个范围。例如：“1, 3-5”表示第1页和第3到5页。",
    split_btn: "下载 PDF",
    split_processing: "处理中...",
    img2pdf_title: "图片转 PDF",
    img2pdf_desc: "将 JPG 和 PNG 图片转换为高质量的 PDF 文档。",
    img2pdf_upload_label: "拖放图片 (JPG, PNG) 到此处",
    img2pdf_preview: "预览",
    img2pdf_btn: "转换为 PDF",
    img2pdf_processing: "转换中...",
    extract_img_title: "提取 PDF 图片",
    extract_img_desc: "自动扫描并提取 PDF 中的所有图片资源。",
    extract_upload_label: "上传 PDF 以提取图片",
    extract_btn: "开始提取图片",
    extract_processing: "正在扫描图片...",
    extract_no_images: "提取失败：文件中不存在图片",
    extract_found_count: "成功提取 {count} 张图片",
    btn_download: "下载",
    convert_title: "PDF 转 Excel/Word",
    convert_desc: "将 PDF 文件转换为 Word 文档、Excel 表格或纯文本。",
    convert_upload_label: "上传要转换的 PDF",
    convert_note: "注意：",
    convert_note_text: "普通模式速度快，适合标准电子文档。AI 辅助优化 Excel 表格结构。",
    convert_note_ocr: "OCR 模式处理速度较慢，但能精准识别扫描件、图片中的文字和表格。",
    convert_btn: "开始转换",
    convert_processing: "处理中",
    convert_ocr_title: "增强型 OCR (适用于扫描件)",
    convert_ocr_desc: "利用 AI 视觉识别图片中的文字和表格。解决空白文档问题。",
    edit_open_pdf: "打开要编辑的 PDF",
    edit_tool_cursor: "选择/移动",
    edit_tool_text: "插入文字",
    edit_tool_image: "插入图片",
    edit_tool_erase: "擦除",
    edit_tool_rect: "矩形",
    edit_tool_circle: "圆形",
    edit_tool_line: "线条",
    edit_tool_stamp: "图章",
    edit_tool_crop: "裁剪页面",
    edit_watermark: "水印",
    edit_undo_tooltip: "撤销 (Ctrl+Z)",
    edit_delete_tooltip: "删除选中元素",
    edit_export_btn: "导出 PDF",
    edit_processing: "处理中...",
    edit_hint: "提示：选中元素后按 Delete 键或点击上方删除按钮可移除。拖拽四角可缩放。Ctrl+Z 撤销。",
    edit_drag_overlay: "松开以打开 PDF",
    prompt_watermark: "输入水印文本：",
    prompt_text: "输入文本：",
    alert_load_fail: "加载 PDF 失败。",
    alert_upload_pdf: "请上传 PDF 文件",
    alert_save_fail: "保存 PDF 失败。",
    alert_merge_fail: "合并 PDF 失败。请确保所有文件都是有效的 PDF。",
    alert_split_fail: "操作失败。",
    alert_convert_fail: "转换失败。",
    alert_convert_empty: "未检测到文本，且未开启 OCR 模式。请开启“增强型 OCR”后重试。",
    alert_scan_detected: "检测到此文件可能是扫描件（无文本层）。是否切换到 AI OCR 模式以提取内容？",
    alert_img2pdf_fail: "转换失败。请检查您的图片文件。",
    alert_only_pdf: "请上传 PDF 文件",
    select_other_file: "选择其他文件",
    start_using: "开始使用",
    total_pages: "共 {count} 页",
    page_counter: "{curr} / {total}",
    crop_area: "裁剪区域",
    settings_language: "语言",
    btn_start_convert: "开始转换",
  },
  en: {
    app_name: "PDF Master",
    pro_badge: "Pro",
    home: "Home",
    edit_pdf: "Editor",
    merge_pdf: "Merge",
    split_pdf: "Split",
    img_to_pdf: "Image to PDF",
    extract_images: "Extract Images",
    convert_pdf: "Convert",
    nav_edit_organize: "Edit & Organize",
    nav_smart_tools: "Smart Tools",
    hero_title: "All-in-One PDF Toolkit",
    hero_desc: "Browser-based, secure, and efficient. Smart document processing. No file uploads needed.",
    start_edit: "Start Editing",
    popular_tools: "Popular Tools",
    tool_desc_edit: "Add text, images, shapes, watermarks, or crop pages. Supports stamps and signatures.",
    tool_desc_merge: "Combine multiple PDFs into one organized document. Supports drag-and-drop reordering.",
    tool_desc_split: "Split documents by page range or extract specific pages.",
    tool_desc_img2pdf: "Convert JPG and PNG images into high-quality PDF documents.",
    tool_desc_convert: "Use AI to convert PDF text and data into Word, Excel, or text formats.",
    tool_desc_extract_img: "Extract all images from PDF documents and save as JPG or PNG.",
    feature_privacy: "Privacy First",
    feature_privacy_desc: "Files are processed locally in your browser",
    feature_speed: "Blazing Fast",
    feature_speed_desc: "WebAssembly powered for native-like performance",
    feature_ai: "AI Powered",
    feature_ai_desc: "Integrated with Google Gemini models",
    upload_click_drag: "Click or drag files here",
    upload_release: "Release to upload",
    upload_formats: "Supported formats",
    merge_title: "Merge PDF Files",
    merge_desc: "Combine multiple PDFs into one document in seconds.",
    merge_upload_label: "Drag & drop PDFs here",
    merge_selected_files: "Selected Files",
    merge_btn: "Merge PDFs Now",
    merge_btn_processing: "Merging...",
    split_title: "Split or Extract Pages",
    split_desc: "Split PDF into multiple files or extract specific pages.",
    split_upload_label: "Upload PDF to split",
    split_change_file: "Change File",
    split_mode_split: "Split into files",
    split_mode_split_desc: "Save ranges as separate PDFs",
    split_mode_extract: "Extract to one file",
    split_mode_extract_desc: "Merge ranges into one PDF",
    split_range_label: "Page Range",
    split_range_placeholder: "e.g., 1-3, 5, 8-10",
    split_range_help: "Use commas to separate ranges. E.g., '1, 3-5' means page 1 and pages 3 to 5.",
    split_btn: "Download PDF",
    split_processing: "Processing...",
    img2pdf_title: "Image to PDF",
    img2pdf_desc: "Convert JPG and PNG images to high-quality PDFs.",
    img2pdf_upload_label: "Drag & drop images (JPG, PNG)",
    img2pdf_preview: "Preview",
    img2pdf_btn: "Convert to PDF",
    img2pdf_processing: "Converting...",
    extract_img_title: "Extract Images",
    extract_img_desc: "Automatically scan and extract all images from PDF.",
    extract_upload_label: "Upload PDF to extract images",
    extract_btn: "Start Extraction",
    extract_processing: "Scanning images...",
    extract_no_images: "Extraction failed: No images found in file",
    extract_found_count: "Successfully extracted {count} images",
    btn_download: "Download",
    convert_title: "PDF to Word/Excel",
    convert_desc: "Convert PDF files to Word documents, Excel tables, or plain text.",
    convert_upload_label: "Upload PDF to convert",
    convert_note: "Note:",
    convert_note_text: "Standard mode is fast. Excel conversion uses AI for structure.",
    convert_note_ocr: "OCR mode is slower but accurately extracts text/tables from images/scans.",
    convert_btn: "Start Conversion",
    convert_processing: "Processing",
    convert_ocr_title: "Enhanced OCR (For Scans)",
    convert_ocr_desc: "Use AI Vision to recognize text and tables in images. Fixes blank outputs.",
    edit_open_pdf: "Open PDF to Edit",
    edit_tool_cursor: "Select/Move",
    edit_tool_text: "Text",
    edit_tool_image: "Image",
    edit_tool_erase: "Erase",
    edit_tool_rect: "Rectangle",
    edit_tool_circle: "Circle",
    edit_tool_line: "Line",
    edit_tool_stamp: "Stamp",
    edit_tool_crop: "Crop",
    edit_watermark: "Watermark",
    edit_undo_tooltip: "Undo (Ctrl+Z)",
    edit_delete_tooltip: "Delete Selected",
    edit_export_btn: "Export PDF",
    edit_processing: "Processing...",
    edit_hint: "Tip: Select element and press Delete to remove. Drag corners to resize. Ctrl+Z to undo.",
    edit_drag_overlay: "Release to open PDF",
    prompt_watermark: "Enter watermark text:",
    prompt_text: "Enter text:",
    alert_load_fail: "Failed to load PDF.",
    alert_upload_pdf: "Please upload a PDF file.",
    alert_save_fail: "Failed to save PDF.",
    alert_merge_fail: "Failed to merge. Ensure all files are valid PDFs.",
    alert_split_fail: "Operation failed.",
    alert_convert_fail: "Conversion failed.",
    alert_convert_empty: "No text found and OCR mode is off. Please enable 'Enhanced OCR' and try again.",
    alert_scan_detected: "This looks like a scanned document (no text found). Switch to AI OCR mode to extract content?",
    alert_img2pdf_fail: "Conversion failed. Check your images.",
    alert_only_pdf: "Please upload a PDF file.",
    select_other_file: "Select another file",
    start_using: "Start Using",
    total_pages: "Total {count} pages",
    page_counter: "{curr} / {total}",
    crop_area: "Crop Area",
    settings_language: "Language",
    btn_start_convert: "Start Conversion",
  },
  fr: {
    app_name: "PDF Master",
    pro_badge: "Pro",
    home: "Accueil",
    edit_pdf: "Éditeur PDF",
    merge_pdf: "Fusionner",
    split_pdf: "Diviser",
    img_to_pdf: "Image en PDF",
    extract_images: "Extraire Images",
    convert_pdf: "Convertir",
    nav_edit_organize: "Éditer & Organiser",
    nav_smart_tools: "Outils Intelligents",
    hero_title: "Boîte à outils PDF complète",
    hero_desc: "Basé sur navigateur, sécurisé et efficace. Traitement intelligent des documents.",
    start_edit: "Commencer l'édition",
    popular_tools: "Outils Populaires",
    tool_desc_edit: "Ajouter texte, images, formes, filigranes ou rogner. Supporte tampons et signatures.",
    tool_desc_merge: "Combiner plusieurs PDF en un seul document. Tri par glisser-déposer.",
    tool_desc_split: "Diviser par plage de pages ou extraire des pages spécifiques.",
    tool_desc_img2pdf: "Convertir images JPG et PNG en PDF de haute qualité.",
    tool_desc_convert: "Utiliser l'IA pour convertir PDF en Word, Excel ou texte.",
    tool_desc_extract_img: "Extraire toutes les images des documents PDF.",
    feature_privacy: "Confidentialité",
    feature_privacy_desc: "Traitement local dans votre navigateur",
    feature_speed: "Ultra Rapide",
    feature_speed_desc: "WebAssembly pour des performances natives",
    feature_ai: "Propulsé par IA",
    feature_ai_desc: "Intégré avec les modèles Google Gemini",
    upload_click_drag: "Cliquez ou glissez des fichiers ici",
    upload_release: "Relâchez pour télécharger",
    upload_formats: "Formats supportés",
    merge_title: "Fusionner des fichiers PDF",
    merge_desc: "Combinez plusieurs PDF en un seul document en quelques secondes.",
    merge_upload_label: "Glissez des PDF ici",
    merge_selected_files: "Fichiers sélectionnés",
    merge_btn: "Fusionner maintenant",
    merge_btn_processing: "Fusion en cours...",
    split_title: "Diviser ou Extraire",
    split_desc: "Divisez un PDF ou extrayez des pages spécifiques.",
    split_upload_label: "Télécharger PDF à diviser",
    split_change_file: "Changer de fichier",
    split_mode_split: "Diviser en fichiers",
    split_mode_split_desc: "Sauvegarder plages comme PDF séparés",
    split_mode_extract: "Extraire en un fichier",
    split_mode_extract_desc: "Fusionner plages en un seul PDF",
    split_range_label: "Plage de pages",
    split_range_placeholder: "ex: 1-3, 5, 8-10",
    split_range_help: "Utilisez des virgules pour séparer. Ex: '1, 3-5' signifie page 1 et pages 3 à 5.",
    split_btn: "Télécharger PDF",
    split_processing: "Traitement...",
    img2pdf_title: "Image en PDF",
    img2pdf_desc: "Convertir JPG et PNG en PDF de haute qualité.",
    img2pdf_upload_label: "Glissez des images (JPG, PNG)",
    img2pdf_preview: "Aperçu",
    img2pdf_btn: "Convertir en PDF",
    img2pdf_processing: "Conversion...",
    extract_img_title: "Extraire Images",
    extract_img_desc: "Scanner et extraire automatiquement toutes les images du PDF.",
    extract_upload_label: "Télécharger PDF pour extraire",
    extract_btn: "Commencer l'extraction",
    extract_processing: "Scan des images...",
    extract_no_images: "Extraction échouée : Aucune image trouvée",
    extract_found_count: "{count} images extraites avec succès",
    btn_download: "Télécharger",
    convert_title: "PDF vers Excel/Word",
    convert_desc: "Convertir PDF en Word, Excel ou texte brut.",
    convert_upload_label: "Télécharger PDF à convertir",
    convert_note: "Note :",
    convert_note_text: "Le mode standard est rapide. La conversion Excel utilise l'IA.",
    convert_note_ocr: "Le mode OCR est plus lent mais extrait le texte des images/scans.",
    convert_btn: "Lancer la conversion",
    convert_processing: "Traitement",
    convert_ocr_title: "OCR Amélioré (Pour scans)",
    convert_ocr_desc: "Utiliser l'IA Vision pour reconnaître le texte dans les images.",
    edit_open_pdf: "Ouvrir PDF à éditer",
    edit_tool_cursor: "Sélection/Déplacer",
    edit_tool_text: "Texte",
    edit_tool_image: "Image",
    edit_tool_erase: "Effacer",
    edit_tool_rect: "Rectangle",
    edit_tool_circle: "Cercle",
    edit_tool_line: "Ligne",
    edit_tool_stamp: "Tampon",
    edit_tool_crop: "Rogner",
    edit_watermark: "Filigrane",
    edit_undo_tooltip: "Annuler (Ctrl+Z)",
    edit_delete_tooltip: "Supprimer sélection",
    edit_export_btn: "Exporter PDF",
    edit_processing: "Traitement...",
    edit_hint: "Astuce : Sélectionnez et appuyez sur Suppr. Glissez les coins pour redimensionner.",
    edit_drag_overlay: "Relâchez pour ouvrir",
    prompt_watermark: "Texte du filigrane :",
    prompt_text: "Saisir le texte :",
    alert_load_fail: "Échec du chargement du PDF.",
    alert_upload_pdf: "Veuillez télécharger un fichier PDF.",
    alert_save_fail: "Échec de la sauvegarde.",
    alert_merge_fail: "Échec de la fusion.",
    alert_split_fail: "Échec de l'opération.",
    alert_convert_fail: "Échec de la conversion.",
    alert_convert_empty: "Aucun texte trouvé. Activez 'OCR Amélioré' et réessayez.",
    alert_scan_detected: "Document scanné détecté (aucun texte). Passer en mode AI OCR ?",
    alert_img2pdf_fail: "Échec de la conversion.",
    alert_only_pdf: "Veuillez télécharger un fichier PDF.",
    select_other_file: "Choisir un autre fichier",
    start_using: "Commencer",
    total_pages: "{count} pages au total",
    page_counter: "{curr} / {total}",
    crop_area: "Zone de coupe",
    settings_language: "Langue",
    btn_start_convert: "Lancer la conversion",
  },
  es: {
    app_name: "PDF Maestro",
    pro_badge: "Pro",
    home: "Inicio",
    edit_pdf: "Editor PDF",
    merge_pdf: "Unir PDF",
    split_pdf: "Dividir PDF",
    img_to_pdf: "Imagen a PDF",
    extract_images: "Extraer Imágenes",
    convert_pdf: "Convertir",
    nav_edit_organize: "Editar y Organizar",
    nav_smart_tools: "Herramientas Inteligentes",
    hero_title: "Kit de herramientas PDF todo en uno",
    hero_desc: "Basado en navegador, seguro y eficiente. Procesamiento inteligente de documentos.",
    start_edit: "Empezar a Editar",
    popular_tools: "Herramientas Populares",
    tool_desc_edit: "Añadir texto, imágenes, formas, marcas de agua. Soporta sellos y firmas.",
    tool_desc_merge: "Combinar múltiples PDFs en uno solo. Ordenar arrastrando.",
    tool_desc_split: "Dividir por rango de páginas o extraer páginas específicas.",
    tool_desc_img2pdf: "Convertir imágenes JPG y PNG a PDF de alta calidad.",
    tool_desc_convert: "Usar IA para convertir PDF a Word, Excel o texto.",
    tool_desc_extract_img: "Extraer todas las imágenes de documentos PDF.",
    feature_privacy: "Privacidad Primero",
    feature_privacy_desc: "Archivos procesados localmente en su navegador",
    feature_speed: "Ultra Rápido",
    feature_speed_desc: "WebAssembly para rendimiento nativo",
    feature_ai: "Impulsado por IA",
    feature_ai_desc: "Integrado con modelos Google Gemini",
    upload_click_drag: "Clic o arrastrar archivos aquí",
    upload_release: "Soltar para subir",
    upload_formats: "Formatos soportados",
    merge_title: "Unir Archivos PDF",
    merge_desc: "Combine múltiples PDFs en un solo documento en segundos.",
    merge_upload_label: "Arrastre PDFs aquí",
    merge_selected_files: "Archivos Seleccionados",
    merge_btn: "Unir PDFs Ahora",
    merge_btn_processing: "Uniendo...",
    split_title: "Dividir o Extraer",
    split_desc: "Divida PDF en múltiples archivos o extraiga páginas.",
    split_upload_label: "Subir PDF a dividir",
    split_change_file: "Cambiar Archivo",
    split_mode_split: "Dividir en archivos",
    split_mode_split_desc: "Guardar rangos como PDFs separados",
    split_mode_extract: "Extraer en un archivo",
    split_mode_extract_desc: "Unir rangos en un solo PDF",
    split_range_label: "Rango de Páginas",
    split_range_placeholder: "ej: 1-3, 5, 8-10",
    split_range_help: "Use comas para separar. Ej: '1, 3-5' significa página 1 y páginas 3 a 5.",
    split_btn: "Descargar PDF",
    split_processing: "Procesando...",
    img2pdf_title: "Imagen a PDF",
    img2pdf_desc: "Convertir JPG y PNG a PDF de alta calidad.",
    img2pdf_upload_label: "Arrastre imágenes (JPG, PNG)",
    img2pdf_preview: "Vista Previa",
    img2pdf_btn: "Convertir a PDF",
    img2pdf_processing: "Convirtiendo...",
    extract_img_title: "Extraer Imágenes",
    extract_img_desc: "Escanear y extraer automáticamente todas las imágenes del PDF.",
    extract_upload_label: "Subir PDF para extraer",
    extract_btn: "Iniciar Extracción",
    extract_processing: "Escaneando imágenes...",
    extract_no_images: "Extracción fallida: No se encontraron imágenes",
    extract_found_count: "{count} imágenes extraídas con éxito",
    btn_download: "Descargar",
    convert_title: "PDF a Excel/Word",
    convert_desc: "Convertir PDF a Word, Excel o texto.",
    convert_upload_label: "Subir PDF a convertir",
    convert_note: "Nota:",
    convert_note_text: "Modo estándar es rápido. Conversión Excel usa IA.",
    convert_note_ocr: "Modo OCR es más lento pero extrae texto de imágenes/escaneos.",
    convert_btn: "Iniciar Conversión",
    convert_processing: "Procesando",
    convert_ocr_title: "OCR Mejorado (Escaneos)",
    convert_ocr_desc: "Usar IA Vision para reconocer texto en imágenes.",
    edit_open_pdf: "Abrir PDF para Editar",
    edit_tool_cursor: "Seleccionar/Mover",
    edit_tool_text: "Texto",
    edit_tool_image: "Imagen",
    edit_tool_erase: "Borrar",
    edit_tool_rect: "Rectángulo",
    edit_tool_circle: "Círculo",
    edit_tool_line: "Línea",
    edit_tool_stamp: "Sello",
    edit_tool_crop: "Recortar",
    edit_watermark: "Marca de agua",
    edit_undo_tooltip: "Deshacer (Ctrl+Z)",
    edit_delete_tooltip: "Eliminar Selección",
    edit_export_btn: "Exportar PDF",
    edit_processing: "Procesando...",
    edit_hint: "Consejo: Seleccione y presione Supr. Arrastre esquinas para redimensionar.",
    edit_drag_overlay: "Suelte para abrir",
    prompt_watermark: "Texto de marca de agua:",
    prompt_text: "Introducir texto:",
    alert_load_fail: "Error al cargar PDF.",
    alert_upload_pdf: "Por favor suba un archivo PDF.",
    alert_save_fail: "Error al guardar PDF.",
    alert_merge_fail: "Error al unir.",
    alert_split_fail: "Operación fallida.",
    alert_convert_fail: "Conversión fallida.",
    alert_convert_empty: "No se encontró texto. Active 'OCR Mejorado' y reintente.",
    alert_scan_detected: "¿Documento escaneado detectado? ¿Cambiar a modo AI OCR?",
    alert_img2pdf_fail: "Conversión fallida.",
    alert_only_pdf: "Por favor suba un archivo PDF.",
    select_other_file: "Seleccionar otro archivo",
    start_using: "Empezar",
    total_pages: "Total {count} páginas",
    page_counter: "{curr} / {total}",
    crop_area: "Área de recorte",
    settings_language: "Idioma",
    btn_start_convert: "Iniciar Conversión",
  },
  it: {
    app_name: "PDF Maestro",
    pro_badge: "Pro",
    home: "Home",
    edit_pdf: "Editor PDF",
    merge_pdf: "Unisci PDF",
    split_pdf: "Dividi PDF",
    img_to_pdf: "Immagine in PDF",
    extract_images: "Estrai Immagini",
    convert_pdf: "Converti",
    nav_edit_organize: "Modifica e Organizza",
    nav_smart_tools: "Strumenti Smart",
    hero_title: "Toolkit PDF Completo",
    hero_desc: "Basato su browser, sicuro ed efficiente. Elaborazione intelligente dei documenti.",
    start_edit: "Inizia Modifica",
    popular_tools: "Strumenti Popolari",
    tool_desc_edit: "Aggiungi testo, immagini, forme, filigrane. Supporta timbri e firme.",
    tool_desc_merge: "Combina più PDF in un unico documento. Riordina trascinando.",
    tool_desc_split: "Dividi per intervallo pagine o estrai pagine specifiche.",
    tool_desc_img2pdf: "Converti immagini JPG e PNG in PDF di alta qualità.",
    tool_desc_convert: "Usa IA per convertire PDF in Word, Excel o testo.",
    tool_desc_extract_img: "Estrai tutte le immagini dai documenti PDF.",
    feature_privacy: "Privacy Prima di Tutto",
    feature_privacy_desc: "File elaborati localmente nel browser",
    feature_speed: "Ultra Veloce",
    feature_speed_desc: "WebAssembly per prestazioni native",
    feature_ai: "Potenziato da IA",
    feature_ai_desc: "Integrato con modelli Google Gemini",
    upload_click_drag: "Clicca o trascina file qui",
    upload_release: "Rilascia per caricare",
    upload_formats: "Formati supportati",
    merge_title: "Unisci File PDF",
    merge_desc: "Combina più PDF in un unico documento in pochi secondi.",
    merge_upload_label: "Trascina PDF qui",
    merge_selected_files: "File Selezionati",
    merge_btn: "Unisci PDF Ora",
    merge_btn_processing: "Unione in corso...",
    split_title: "Dividi o Estrai",
    split_desc: "Dividi PDF in più file o estrai pagine specifiche.",
    split_upload_label: "Carica PDF da dividere",
    split_change_file: "Cambia File",
    split_mode_split: "Dividi in file",
    split_mode_split_desc: "Salva intervalli come PDF separati",
    split_mode_extract: "Estrai in un file",
    split_mode_extract_desc: "Unisci intervalli in un solo PDF",
    split_range_label: "Intervallo Pagine",
    split_range_placeholder: "es: 1-3, 5, 8-10",
    split_range_help: "Usa virgole per separare. Es: '1, 3-5' significa pagina 1 e pagine da 3 a 5.",
    split_btn: "Scarica PDF",
    split_processing: "Elaborazione...",
    img2pdf_title: "Immagine in PDF",
    img2pdf_desc: "Converti JPG e PNG in PDF di alta qualità.",
    img2pdf_upload_label: "Trascina immagini (JPG, PNG)",
    img2pdf_preview: "Anteprima",
    img2pdf_btn: "Converti in PDF",
    img2pdf_processing: "Conversione...",
    extract_img_title: "Estrai Immagini",
    extract_img_desc: "Scansiona ed estrai automaticamente tutte le immagini dal PDF.",
    extract_upload_label: "Carica PDF per estrarre",
    extract_btn: "Inizia Estrazione",
    extract_processing: "Scansione immagini...",
    extract_no_images: "Estrazione fallita: Nessuna immagine trovata",
    extract_found_count: "{count} immagini estratte con successo",
    btn_download: "Scarica",
    convert_title: "PDF a Excel/Word",
    convert_desc: "Converti PDF in Word, Excel o testo.",
    convert_upload_label: "Carica PDF da convertire",
    convert_note: "Nota:",
    convert_note_text: "Modalità standard è veloce. Conversione Excel usa IA.",
    convert_note_ocr: "Modalità OCR è più lenta ma estrae testo da immagini/scansioni.",
    convert_btn: "Inizia Conversione",
    convert_processing: "Elaborazione",
    convert_ocr_title: "OCR Avanzato (Scansioni)",
    convert_ocr_desc: "Usa IA Vision per riconoscere testo in immagini.",
    edit_open_pdf: "Apri PDF da Modificare",
    edit_tool_cursor: "Seleziona/Sposta",
    edit_tool_text: "Testo",
    edit_tool_image: "Immagine",
    edit_tool_erase: "Gomma",
    edit_tool_rect: "Rettangolo",
    edit_tool_circle: "Cerchio",
    edit_tool_line: "Linea",
    edit_tool_stamp: "Timbro",
    edit_tool_crop: "Ritaglia",
    edit_watermark: "Filigrana",
    edit_undo_tooltip: "Annulla (Ctrl+Z)",
    edit_delete_tooltip: "Elimina Selezione",
    edit_export_btn: "Esporta PDF",
    edit_processing: "Elaborazione...",
    edit_hint: "Consiglio: Seleziona e premi Canc. Trascina angoli per ridimensionare.",
    edit_drag_overlay: "Rilascia per aprire",
    prompt_watermark: "Testo filigrana:",
    prompt_text: "Inserisci testo:",
    alert_load_fail: "Caricamento PDF fallito.",
    alert_upload_pdf: "Carica un file PDF.",
    alert_save_fail: "Salvataggio fallito.",
    alert_merge_fail: "Unione fallita.",
    alert_split_fail: "Operazione fallita.",
    alert_convert_fail: "Conversione fallita.",
    alert_convert_empty: "Nessun testo trovato. Attiva 'OCR Avanzato' e riprova.",
    alert_scan_detected: "Documento scansionato rilevato? Passare a modalità AI OCR?",
    alert_img2pdf_fail: "Conversión fallita.",
    alert_only_pdf: "Carica un file PDF.",
    select_other_file: "Seleziona altro file",
    start_using: "Inizia",
    total_pages: "Totale {count} pagine",
    page_counter: "{curr} / {total}",
    crop_area: "Area ritaglio",
    settings_language: "Lingua",
    btn_start_convert: "Inizia Conversione",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};